### ISSUE TITLE
dark mode issues

### ISSUE THREAD

**Issue by ivanooi** [eclipse/windowbuilder#48] opened 2021-09-27 22:59 UTC
Eclipse IDE for Java Developers (includes Incubating components)
Version: 2021-09 (4.21.0)
Build id: 20210910-1417
OS: Mac OS X, v.10.15.7, x86_64 / cocoa
Java vendor: Oracle Corporation
Java runtime version: 16.0.2+7-67
Java version: 16.0.2

<img width="716" alt="Greenshot 2021-09-28 06 55 57" src="https://user-images.githubusercontent.com/15061028/134996533-8f505cef-fe75-4299-bde1-c3d29c4ad297.png">

Nebula Widgets properties issues : 
 
<img width="417" alt="Greenshot 2021-09-28 10 50 34" src="https://user-images.githubusercontent.com/15061028/135014702-edef9700-cffe-4a72-a892-370200ad327e.png">

**Comment by lcaron** [comment] 2021-10-21 19:40
The second part of this bug is a duplicate of #53 

For the first part can you provide the custom component ?

**Comment by vogella** [comment] 2021-11-30 08:44
One location with a hard-coded color value is org.eclipse.wb.core.gef.header.Headers#getColorHeader;

**Comment by vogella** [comment] 2021-12-21 14:44
Looks fine on latest 2021-12 release with Linux for me.

![window-builder](https://user-images.githubusercontent.com/139910/146948520-617dc91b-8c96-41a2-b3f2-3339d69013af.png)

As we have not heard back from @ivanooi I marked this one as closed.

**Closed by vogella** 2021-12-21 14:44 UTC
